### ISSUE TITLE
banterbot crash: `botname` doesn't exist

### ISSUE THREAD

**Issue by jmdejong** [RussellChamp/tilde-projects#3]
Currently banterbot keeps crashing as soon as it gets a message.

The most probable cause, looking at the commit history, is that it tests if `botname` occurst in the message, but the variable `botname` doesn't exist in the code.

This problem started occuring after banterbot crashed on a large figlet text (thereby running the new code)

EDIT just found the log. It is indeed the botname variable:

    Traceback (most recent call last):
      File "./banterbot.py", line 334, in <module>
        listen()
      File "./banterbot.py", line 323, in listen
        if ircmsg.find(":" + botname + ":") != -1:
    NameError: global name 'botname' is not defined

**Comment by RussellChamp** [comment]
Oh no! How do I git issues. This is new to me... Thanks for the issue! Is this still happening? I've had derpy bad commits every once in a while but usually resolve them on my own pretty quickly.

**Comment by RussellChamp** [comment]
Umm... how do I mark "Resolved" and not just closed? I had a bad commit for a little while but fixed the issue. This has been resolved!

**Comment by jmdejong** [comment]
I think "closed" can mean "resolved" in this case. There are some way to automatically resolve it if you would say something like `fixes #3` in a commit message, but I don't think that eventually just does the same.
